src/application/projeto/models/Projeto.java
package application.projeto.models;

import application.atividade.models.Atividade;
import com.sun.istack.internal.NotNull;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class Projeto {

    private Integer codigo;
    private String nome;
    private List<Atividade> atividades = new ArrayList<>();

    private String descricao;

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<Atividade> getAtividades() {
        return atividades;
    }

    public void setAtividades(List<Atividade> atividades) {
        this.atividades = atividades;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getCodigo());
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Projeto)) {
            return false;
        }
        final Projeto other = (Projeto) obj;

        return Objects.equals(this.codigo, other.codigo);
    }

}

src/application/projeto/models/ProjetoRepository.java
package application.projeto.models;

import java.util.ArrayList;
import java.util.List;

public class ProjetoRepository {

    private static List<Projeto> projetos = new ArrayList<>();

    public static void salvar(Projeto projeto) {

        if(!ProjetoRepository.projetos.contains(projeto)) {
            ProjetoRepository.projetos.add(projeto);
        }
    }

    public static void excluir(Projeto projeto) {
        ProjetoRepository.projetos.remove(projeto);
    }

    public static Projeto getProjeto(Integer codigo) {

        return ProjetoRepository.projetos.stream()
                .filter(projeto -> projeto.getCodigo().equals(codigo)).findFirst().orElse(null);
    }

    public static List<Projeto> getProjetos() {
        return ProjetoRepository.projetos;
    }



}

src/application/atividade/controllers/AtividadeController.java
package application.atividade.controllers;

import application.atividade.models.Atividade;
import application.atividade.models.AtividadeRepository;
import application.atividade.models.enums.SituacaoAtividade;
import application.projeto.models.Projeto;
import application.projeto.models.ProjetoRepository;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@ViewScoped
public class AtividadeController {

    private Integer codigoProjeto;
    private Projeto projeto;
    private Atividade atividade;
    private List<Atividade> atividades = new ArrayList<>();

    public AtividadeController() {
        this.projeto = new Projeto();
    }

    @PostConstruct
    public void init() {
        codigoProjeto = Integer.valueOf(
                FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("codigo")
        );
        this.atualizarListaAtividades();
        this.projeto = ProjetoRepository.getProjeto(codigoProjeto);
        this.novo();
    }

    public void novo() {
        atividade = new Atividade();
        atividade.setProjeto(projeto);
    }

    private void atualizarListaAtividades() {
        atividades = AtividadeRepository.getAtividadesByProjeto(codigoProjeto);
//        atividades = AtividadeRepository.getAtividades();
    }

    public void salvar() {
        AtividadeRepository.salvar(atividade);
        this.atualizarListaAtividades();
        this.novo();
    }

    public void excluir(Atividade atividade) {
        AtividadeRepository.excluir(atividade);
        this.atualizarListaAtividades();
    }

    public Projeto getProjeto() {
        return projeto;
    }

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

    public SituacaoAtividade[] getSituacoesAtividade(){
        return SituacaoAtividade.values();
    }

    public Atividade getAtividade() {
        return atividade;
    }

    public void setAtividade(Atividade atividade) {
        this.atividade = atividade;
    }

    public List<Atividade> getAtividades() {
        return atividades;
    }

    public void setAtividades(List<Atividade> atividades) {
        this.atividades = atividades;
    }
}

src/application/projeto/controllers/ProjetoController.java
package application.projeto.controllers;


import application.projeto.models.Projeto;
import application.projeto.models.ProjetoRepository;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@ViewScoped
public class ProjetoController {

    private Projeto projeto;
    private List<Projeto> projetos = new ArrayList<>();

    public ProjetoController() {
        novo();
        atualizarListaProjetos();
    }

    public void novo() {
        projeto = new Projeto();
    }

    private void atualizarListaProjetos() {
        projetos = ProjetoRepository.getProjetos();
    }

    public void salvar() {
        ProjetoRepository.salvar(projeto);
        this.atualizarListaProjetos();
        this.novo();
    }

    public void excluir(Projeto projeto) {
        ProjetoRepository.excluir(projeto);
        this.atualizarListaProjetos();
    }

    public Projeto getProjeto() {
        return projeto;
    }

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

    public List<Projeto> getProjetos() {
        return projetos;
    }

    public void setProjetos(List<Projeto> projetos) {
        this.projetos = projetos;
    }
}

web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"/>
    <h:outputStylesheet library="css" name="table-style.css"/>
    <title>Projetos</title>
</h:head>
<h:body>

    <div class="container" style="margin-top: 15px; padding: 0px !important;">
        <div class="alert alert-secondary">
            <h3 class="text-center">Projetos</h3>
        </div>
    </div>

    <h:form class="container">
        <div class="row">
            Código: <h:inputText styleClass="form-control" id="codigo" value="#{projetoController.projeto.codigo}"/>
            <h:message for="codigo"/>
        </div>
        <div class="row">
            Descrição: <h:inputText styleClass="form-control" value="#{projetoController.projeto.descricao}"/>
        </div>
        <div class="row">
            Nome: <h:inputText styleClass="form-control" value="#{projetoController.projeto.nome}"/>
        </div>
        <div class="row" style="margin-top: 15px">
            <h:commandButton class="btn btn-primary btn-sm" style="width: 50%" value="Salvar Projeto"
                             action="#{projetoController.salvar()}"/>
            <h:commandButton class="btn btn-dark btn-sm" style="width: 50%" value="Nova Atividade"
                             action="#{projetoController.novo()}"/>
        </div>

        <div class="row">
            <h:dataTable styleClass="order-table"
                         headerClass="order-table-header"
                         rowClasses="order-table-odd-row,order-table-even-row"
                         value="#{projetoController.projetos}" var="p">
                <h:column headerText="Codigo">
                    <f:facet name="header">Código</f:facet>
                    <h:commandLink action="#{projetoController.setProjeto(p)}">
                        #{p.codigo}
                    </h:commandLink>
                </h:column>
                <h:column>
                    <f:facet name="header">Nome</f:facet>
                    #{p.nome}
                </h:column>
                <h:column>
                    <f:facet name="header">Descrição</f:facet>
                    #{p.descricao}
                </h:column>
                <h:column>
                    <f:facet name="header">Ações</f:facet>
                    <h:commandLink action="projeto.xhtml" value="abrir">
                        <f:param name="codigo" value="#{p.codigo}"/>
                    </h:commandLink>
                    <h:commandLink action="#{projetoController.setProjeto(p)}"> Editar </h:commandLink>
                    <h:commandLink action="#{projetoController.excluir(p)}"> Excluir </h:commandLink>
                </h:column>
            </h:dataTable>
        </div>
    </h:form>

</h:body>
</html>

web/projeto.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"/>
    <h:outputStylesheet library="css" name="table-style.css"/>

    <title>Atividades Projeto</title>
</h:head>
<h:body>

    <div class="container" style="margin-top: 15px; padding: 0px !important;">
        <div class="alert alert-secondary">
            <h3 class="text-center">Cadastro de Atividades</h3>
        </div>
    </div>

    <h:form class="container">

        <h:commandButton class="btn btn-link" style="width: 100%;text-align: end" action="index.xhtml"
                         value="Voltar para listagem de projetos" />
        <div class="row">
            <p><b>Nome: </b>#{atividadeController.projeto.nome}</p>
        </div>
        <div class="row">
            <p><b>Descrição: </b>#{atividadeController.projeto.descricao}</p>
        </div>
        <div class="row">
            Código Atividade: <h:inputText styleClass="form-control" id="codigo" value="#{atividadeController.atividade.codigo}"/>
            <h:message for="codigo"/>
        </div>
        <div class="row">
            Nome: <h:inputText styleClass="form-control" value="#{atividadeController.atividade.nome}"/>
        </div>
        <div class="row">
            Situação Atividade
            <h:selectOneMenu styleClass="form-control" id="areas" value="#{atividadeController.atividade.situacaoAtividade}">
                <f:selectItems value="#{atividadeController.situacoesAtividade}"/>
            </h:selectOneMenu>
        </div>
        <div class="row">
            <div class="column" style="width: 50%">
                Quantidade Esforço: <h:inputText styleClass="form-control"
                                                 value="#{atividadeController.atividade.quantidadeEsforco}"
                                                 converterMessage="Please enter digits only."/>
            </div>
            <div class="column" style="width: 50%">
                Tempo Utilizado: <h:inputText styleClass="form-control"
                                              value="#{atividadeController.atividade.quantidadeTempoGasto}"
                                              converterMessage="Please enter digits only."/>
            </div>
        </div>
        <div class="row" style="margin-top: 15px">
            <h:commandButton class="btn btn-primary btn-sm" style="width: 50%" value="Salvar Atividade"
                             action="#{atividadeController.salvar()}"/>
            <h:commandButton class="btn btn-dark btn-sm" style="width: 50%" value="Nova Atividade"
                             action="#{atividadeController.novo()}"/>
        </div>

        <div class="row">
            <h:dataTable styleClass="order-table"
                         headerClass="order-table-header"
                         rowClasses="order-table-odd-row,order-table-even-row"
                         value="#{atividadeController.atividades}" var="a">
                <h:column headerText="Codigo">
                    <f:facet name="header">Código</f:facet>
                    <h:commandLink action="#{atividadeController.setAtividade(a)}">
                        #{a.codigo}
                    </h:commandLink>
                </h:column>
                <h:column headerText="Cod. Projeto">
                    <f:facet name="header">Código</f:facet>
                        #{a.projeto.codigo}
                </h:column>
                <h:column>
                    <f:facet name="header">Nome</f:facet>
                    #{a.nome}
                </h:column>
                <h:column>
                    <f:facet name="header">Quant. Esforço</f:facet>
                    #{a.quantidadeEsforco}
                </h:column>
                <h:column>
                    <f:facet name="header">Quant. Tempo Gasto</f:facet>
                    #{a.quantidadeTempoGasto}
                </h:column>

                <h:column>
                    <f:facet name="header">Quant. Tempo Gasto</f:facet>
                    #{a.situacaoAtividade.nome}
                </h:column>
                <h:column>
                    <f:facet name="header">Ações</f:facet>
                    <h:commandLink action="#{atividadeController.setAtividade(a)}"> Editar </h:commandLink>
                    <h:commandLink action="#{atividadeController.excluir(a)}"> Excluir </h:commandLink>
                </h:column>
            </h:dataTable>
        </div>

    </h:form>
</h:body>
</html>